version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: area_postgres
    restart: always
    environment:
      POSTGRES_DB: area_db
      POSTGRES_USER: area_user
      POSTGRES_PASSWORD: area_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U area_user -d area_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: