name: Chocolatine

"on":
  push:
    branches:
      - "*"
      - "!**dev/*"
      - "!**ga-ignore-*"
  pull_request:
    branches:
      - "*"
      - "!**dev/*"
      - "!**ga-ignore-*"

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-7.git

jobs:
  build-application-server:
    name: Build Application Server
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install
        working-directory: application-server

      - name: Building Application Server
        run: npm run build
        working-directory: application-server

  build-web-client:
    name: Build Web Client
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install
        working-directory: web-client

      - name: Building Web Client
        run: npm run build
        working-directory: web-client

  build-mobile-client:
    name: Build Mobile Client
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 25.2.9519653

      - name: Install Android SDK platforms
        run: |
          yes | $ANDROID_HOME/cmdline-tools/16.0/bin/sdkmanager "platforms;android-34"
          yes | $ANDROID_HOME/cmdline-tools/16.0/bin/sdkmanager "build-tools;34.0.0"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"

      - name: Installing Dependencies
        run: flutter pub get
        working-directory: mobile-client

      - name: Clean build directory
        run: flutter clean
        working-directory: mobile-client

      - name: Regenerate Android files
        run: |
          rm -rf android/app/src/main/java
          flutter create --platforms=android .
        working-directory: mobile-client

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses
        working-directory: mobile-client

      - name: Verify Flutter configuration
        run: flutter doctor -v
        working-directory: mobile-client

      - name: Build APK
        run: flutter build apk --release --verbose
        working-directory: mobile-client

  test-application-server:
    name: Test Application Server
    runs-on: ubuntu-latest
    needs: build-application-server
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install
        working-directory: application-server

      - name: Running Unit Tests
        run: npm test
        working-directory: application-server

      - name: Running Integration Tests
        run: npm run test:e2e
        working-directory: application-server

  test-web-client:
    name: Test Web Client
    runs-on: ubuntu-latest
    needs: build-web-client
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install
        working-directory: web-client

      - name: Running Tests
        run: npm run test:run
        working-directory: web-client

  repository_mirroring:
    name: Repository Mirroring
    runs-on: ubuntu-latest
    needs: [test-application-server, test-web-client, build-mobile-client]
    if: ${{ github.event.repository.full_name != 'EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-7' }}
    steps:
      - name: Checking Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }} # valid-secret
