name: Chocolatine

"on":
  push:
    branches:
      - "*"
      - "!**dev/*"
      - "!**ga-ignore-*"
  pull_request:
    branches:
      - "*"
      - "!**dev/*"
      - "!**ga-ignore-*"

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-7.git

jobs:
  build-application-server:
    name: Build Application Server
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install
        working-directory: application-server

      - name: Building Application Server
        run: npm run build
        working-directory: application-server

  repository_mirroring:
    name: Repository Mirroring
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.full_name != 'EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-7' }}
    steps:
      - name: Checking Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }} # valid-secret
